services:
  postgres:
    image: postgres:alpine
    container_name: library-postgres
    command: -p $POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    restart: always
    networks:
      - api_network
    volumes:
      - postgres_volume:/var/lib/postgresql/data

networks:
  api_network:

volumes:
  postgres_volume: