version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: library
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
